server:
  port: 8763
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    inmemory: true
    pool:
        enabled: false
  mail:
    host: smtp.163.com
    username: qq41335735@163.com
    password: qqo12345
    enable: true
    smtp:
        auth: true
    starttls:
        enable: true
        required: true